// <auto-generated />
namespace CoffeeShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ItemNameisnowanindexandmustbeunique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ItemNameisnowanindexandmustbeunique));
        
        string IMigrationMetadata.Id
        {
            get { return "201808272119484_Item Name is now an index and must be unique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
